### ISSUE TITLE
Failed to establish new connection

### ISSUE THREAD

**Issue by hunteraaaa** [cskoglun/ciscodnacbackupctl#17]
Hi, could I have a bit of help with this please? I'm trying to set this up on our DNA-C backup server but keep getting the following error and unsure what I am doing wrong when setting the config to connect to our DNA-C application:

[admin@cls-sys-bck-201 ~]$ ciscodnacbackupctl purge --keep 3 --incompatible
Traceback (most recent call last):
  File "/home/admin/.local/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/admin/.local/lib/python3.9/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib64/python3.9/socket.py", line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/admin/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/admin/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/home/admin/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/home/admin/.local/lib/python3.9/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/home/admin/.local/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f9f7039ee20>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/admin/.local/lib/python3.9/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/home/admin/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/home/admin/.local/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='maglev-master-172-31-0-17', port=443): Max retries exceeded with url: /dna/system/api/v1/auth/token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9f7039ee20>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/admin/.local/bin/ciscodnacbackupctl", line 8, in <module>
    sys.exit(entry())
  File "/home/admin/.local/lib/python3.9/site-packages/ciscodnacbackupctl/cli.py", line 367, in entry
    cli(obj={})
  File "/home/admin/.local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/admin/.local/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/admin/.local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/admin/.local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/admin/.local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/admin/.local/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/admin/.local/lib/python3.9/site-packages/ciscodnacbackupctl/cli.py", line 282, in purge
    cli = ciscodnacbackupctl.Api().CLI(debug=ctx.obj["DEBUG"])
  File "/home/admin/.local/lib/python3.9/site-packages/ciscodnacbackupctl/__init__.py", line 39, in __init__
    self._auth()
  File "/home/admin/.local/lib/python3.9/site-packages/ciscodnacbackupctl/__init__.py", line 59, in _auth
    data = self._request(type="auth", url=url)
  File "/home/admin/.local/lib/python3.9/site-packages/ciscodnacbackupctl/__init__.py", line 149, in _request
    response = requests.request(
  File "/home/admin/.local/lib/python3.9/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/admin/.local/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/admin/.local/lib/python3.9/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/admin/.local/lib/python3.9/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='maglev-master-172-31-0-17', port=443): Max retries exceeded with url: /dna/system/api/v1/auth/token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9f7039ee20>: Failed to establish a new connection: [Errno -2] Name or service not known'))

**Comment by robertcsapo** [comment]
It's because the script can't connect to ```maglev-master-172-31-0-17``` hostname
* ```requests.exceptions.ConnectionError: HTTPSConnectionPool(host='maglev-master-172-31-0-17', port=443): Max retries exceeded with url: /dna/system/api/v1/auth/token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9f7039ee20>: Failed to establish a new connection: [Errno -2] Name or service not known'))```

Please use the Cisco DNA Center ```Enterprise Port Address```
* https://www.cisco.com/c/en/us/td/docs/cloud-systems-management/network-automation-and-management/dna-center/2-3-3/install_guide/2ndgen/b_cisco_dna_center_install_guide_2_3_3_2ndGen/m_plan_deployment_2_3_3_2ndgen.html#concept_t3c_dbj_sfb

**Comment by hunteraaaa** [comment]
Thanks for the update and response.

I've amended the address to use the enterprise port address on our DNAC appliance which is 172.31.0.5 but this time get a connection timed out error.  Routing has been checked and the backup server can reach the default gateway that the DNAC appliance resides on which is 172.31.0.1, but is unable to get to the enterprise address of 172.31.0.5.  The DNAC appliance is reachable via https://172.31.0.5 but it seems to be unreachable via this.

"requests.exceptions.ConnectionError: HTTPSConnectionPool(host='172.31.0.5', port=443): Max retries exceeded with url: /dna/system/api/v1/auth/token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f335ab0ad30>: Failed to establish a new connection: [Errno 110] Connection timed out'))"

Could this be something not configured correctly on our DNAC appliance, or an issue with it that would need a TAC raising?

**Comment by robertcsapo** [comment]
Could you clarify where you are running the script (```ciscodnacbackupctl```) from?
Because it's often the same DNAC URL that you reach the DNAC UI.

If the script can't connect (time out), you can test ```curl https://sandboxdnac.cisco.com``` (change to your DNAC URL) to see if it connects.
