### ISSUE TITLE
delete is not working in docker version, as the argument passed by click is a tuple and the typecheck doesn't accept that

### ISSUE THREAD

**Issue by Ivanszky** [cskoglun/ciscodnacbackupctl#22]
Hi Robert,

do you plan to create a docker image based on the latest master branch version? ( as delete is not working with the current docker version)

$ docker run -it -e DNAC_CONFIG=*** robertcsapo/ciscodnacbackupctl delete --backup_id be969b09-e13d-4880-8c40-f10cefecf34a
Traceback (most recent call last):
  File "/usr/local/bin/ciscodnacbackupctl", line 33, in <module>
    sys.exit(load_entry_point('ciscodnacbackupctl', 'console_scripts', 'ciscodnacbackupctl')())
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/app/ciscodnacbackupctl/cli.py", line 216, in delete
    cli.delete(id)
  File "/app/ciscodnacbackupctl/__init__.py", line 342, in delete
    raise TypeError(f"Incorrect type for backup_id - {type(backup_id)}")
TypeError: Incorrect type for backup_id - <class 'tuple'>

kind regards,
Gabor

**Comment by robertcsapo** [comment]
Szia Gabor

I've published the latest 0.2.11.
Can you try this before I replace the latest version?

```docker run -it --rm robertcsapo/ciscodnacbackupctl:0.2.1```

**Comment by Ivanszky** [comment]
Hi Robert,

that version works perfectly, thank you very much!

[Thu Apr 06 06:07:17 UTC] maglev@192.168.0.2 (maglev-master-192-168-0-2) ~
$ docker run -it --rm -e DNAC_CONFIG=***** robertcsapo/ciscodnacbackupctl:0.2.11 delete --backup_id dd9548c0-41ca-46d4-b376-80a223adb4a0
[06:07:59] Deleted backup (backup_id='dd9548c0-41ca-46d4-b376-80a223adb4a0')
