### ISSUE TITLE
Creating backup gives a python error

### ISSUE THREAD

**Issue by fatman00** [cskoglun/ciscodnacbackupctl#4]
```
user@dnac-backup:~$ ciscodnacbackupctl create --name back03
Traceback (most recent call last):
  File "/usr/local/bin/ciscodnacbackupctl", line 11, in <module>
    sys.exit(cli())
  File "/usr/lib/python3/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/ciscodnacbackupctl/cli.py", line 205, in create
    cli.create(name)
  File "/usr/local/lib/python3.8/dist-packages/ciscodnacbackupctl/__init__.py", line 293, in create
    data = self.api._request(type="post", url=url, payload=payload)
  File "/usr/local/lib/python3.8/dist-packages/ciscodnacbackupctl/__init__.py", line 249, in _request
    raise Exception("Error: Not found")
Exception: Error: Not found
```

Running version 0.2.2:
```
$ ciscodnacbackupctl --version
ciscodnacbackupctl, version 0.2.2
$ python3 --version
Python 3.8.0
```

Ubuntu 18.04.5 LTS

**Comment by robertcsapo** [comment]
Fixed in 0.2.3 release, there was a typo in the script. Sorry for that.

```pip3 install ciscodnacbackupctl==0.2.3```

```
ciscodnacbackupctl create --name back03
Creating backup with id: 234baed6-4b20-4d33-936a-8cce7bc2f62f
```

```
ciscodnacbackupctl progress
BACKUP_ID                             BACKUP_SIZE    DESCRIPTION    ID                                    OPERATION    PROGRESS_IN_PERCENTAGE    START_TIMESTAMP      STATUS
234baed6-4b20-4d33-936a-8cce7bc2f62f  354M           back03         234baed6-4b20-4d33-936a-8cce7bc2f62f  BACKUP       50%                       2021-06-21 11:04:28  PENDING
```

```
ciscodnacbackupctl list | grep -i back03
234baed6-4b20-4d33-936a-8cce7bc2f62f  17G            TRUE          back03              2021-06-21 11:12:22  2021-06-21 11:04:52  SUCCESS
```
